import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Snow from "./components/ui/snow";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative">
        <Snow />
        <div style={{ position: "relative", zIndex: 1 }}> 
          {children}
        </div>
      </body>
    </html>
  );
}
//with z index make sure things like form are not obscured by the snow
/*
zIndex 1 →  form / UI
zIndex 0 → (default content)
zIndex -1 → snow canvas
*/
